#!/usr/bin/env ruby
# frozen_string_literal: true

require 'date'

require 'sequel'

MATCHES = 19
MINIMUM = 7
YEAR = 365

Leaf = Struct.new(:match_id, :start_time, :outcome)

def prior(date, years)
  d = Date.parse(date) - (years * YEAR)
  d.strftime('%Y-%m-%d')
end

def side_playing_values(data, type)
  h = Hash.new(0)

  f = 1.0 / data.size

  data.each do |x|
    h[x] += f
  end

  if type == 'home'
    [h['home_win'], h['draw'], h['away_win']]
  else
    [h['away_win'], h['draw'], h['home_win']]
  end
end

def win_lose_values(data, type)
  win = 0.0
  lose = 0.0

  f = 1.0 / data.size

  data.each do |x|
    if type == 'home'
      if x == 'home_win'
        win += f
      else
        lose += f
      end
    elsif x == 'away_win'
      win += f
    else
      lose += f
    end
  end

  [win, lose]
end

def outcomes(tree, team_id, date, type)
  tree[team_id][type].select { |l| l.start_time < date }[0...MATCHES]
end

def table_to_hash(table)
  h = {}
  DB["SELECT * FROM #{table}"].each do |row|
    h[row[:id]] = row
  end
  h
end

def balance(home_wins, away_wins)
  if home_wins.zero?
    if away_wins.zero?
      return 0.0
    else
      return -away_wins
    end
  elsif away_wins.zero?
    return home_wins
  else
    return home_wins - away_wins
  end
end

target_date = ARGV.shift

if target_date.nil?
  puts 'Need to supply a date to split the data on'
  exit 1
end

t0 = Time.now

start_date = prior(target_date, 3)

DB = Sequel.connect('sqlite://matches.sqlite3')

teams = table_to_hash('teams')
comps = table_to_hash('competitions')

top_tier_competitions = DB['SELECT id FROM competitions WHERE top_tier = true'].map { |x| x[:id] }

puts "[EXTRACT] Tree building from #{start_date} to #{target_date}"
tree = {}
t1 = Time.now
DB["SELECT id, home_team_id, away_team_id, start_time, outcome FROM matches WHERE start_time BETWEEN ? AND ? AND competition_id IN ? ORDER BY start_time DESC", start_date, target_date, top_tier_competitions].each do |match|
  tree[match[:home_team_id]] = { home: [], away: [] } unless tree.key?(match[:home_team_id])
  tree[match[:away_team_id]] = { home: [], away: [] } unless tree.key?(match[:away_team_id])

  tree[match[:home_team_id]][:home] << Leaf.new(match[:id], match[:start_time].to_s, match[:outcome])
  tree[match[:away_team_id]][:away] << Leaf.new(match[:id], match[:start_time].to_s, match[:outcome])
end
t2 = Time.now
puts "[EXTRACT] Tree build in #{t2 - t1} seconds"
puts "[EXTRACT] Extracting matches before #{target_date} into historical.txt"

t1= Time.now
r = 0
f = File.open('historical.txt', 'w')
DB['SELECT * FROM matches WHERE start_time BETWEEN ? AND ? AND competition_id IN ? ORDER BY start_time', start_date, target_date, top_tier_competitions].each do |match|
  home_matches = outcomes(tree, match[:home_team_id], match[:start_time].to_s, :home).map(&:outcome)
  next if home_matches.size < MINIMUM

  away_matches = outcomes(tree, match[:away_team_id], match[:start_time].to_s, :away).map(&:outcome)
  next if away_matches.size < MINIMUM

  r += 1

  ho = win_lose_values(home_matches, 'home')
  ao = win_lose_values(away_matches, 'away')

  f.puts '---'
  f.puts balance(ho[0], ao[0])
  f.puts "match_id #{match[:id]}"
  f.puts "outcome #{match[:outcome]}"
  f.puts "start_time #{match[:start_time]}"
  f.puts "home_team #{teams[match[:home_team_id]][:name]}"
  f.puts "away_team #{teams[match[:away_team_id]][:name]}"
  f.puts "competition #{comps[match[:competition_id]][:name]}"
end
f.close
t2 = Time.now
puts "[EXTRACT] Historical data written in #{t2 - t1} seconds (#{r} records)"
puts "[EXTRACT] Extracting matches on #{target_date} into target.txt"

t1 = Time.now
r = 0
t = File.open('target.txt', 'w')
DB['SELECT * FROM matches WHERE start_time = ? AND competition_id IN ?', target_date, top_tier_competitions].each do |match|
  home_matches = outcomes(tree, match[:home_team_id], match[:start_time].to_s, :home).map(&:outcome)
  next if home_matches.size < MINIMUM

  away_matches = outcomes(tree, match[:away_team_id], match[:start_time].to_s, :away).map(&:outcome)
  next if away_matches.size < MINIMUM

  r += 1

  ho = win_lose_values(home_matches, 'home')
  ao = win_lose_values(away_matches, 'away')

  t.puts '---'
  t.puts balance(ho[0], ao[0])
  t.puts "match_id #{match[:id]}"
  t.puts "start_time #{match[:start_time]}"
  t.puts "home_team #{teams[match[:home_team_id]][:name]}"
  t.puts "away_team #{teams[match[:away_team_id]][:name]}"
  t.puts "competition #{comps[match[:competition_id]][:name]}"
end
t.close
t2 = Time.now
puts "[EXTRACT] Target data written in #{t2 - t1} seconds (#{r} records)"
puts "[EXTRACT] Run in #{t2 - t0} seconds"
